# Generated by Django 4.2.7 on 2023-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_App', '0003_author_remove_audio_author_remove_document_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='audio',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='document',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='image',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='video',
            name='theme',
        ),
        migrations.AddField(
            model_name='audio',
            name='themes',
            field=models.ManyToManyField(to='repo_App.theme'),
        ),
        migrations.AddField(
            model_name='document',
            name='themes',
            field=models.ManyToManyField(to='repo_App.theme'),
        ),
        migrations.AddField(
            model_name='image',
            name='themes',
            field=models.ManyToManyField(to='repo_App.theme'),
        ),
        migrations.AddField(
            model_name='video',
            name='themes',
            field=models.ManyToManyField(to='repo_App.theme'),
        ),
    ]
