# Generated by Django 4.2.7 on 2023-11-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo_App', '0004_theme_remove_audio_theme_remove_document_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Resumen',
            new_name='resumen',
        ),
    ]
